### PR TITLE
testing build with pandas increase 1.3.2 -> 1.34

### PR DESCRIPTION
**Pull request by spoonerf**

### CODE REVIEW

**Comment by pabloarosado** [comment]
This PR was created because [this other PR](https://github.com/owid/importers/pull/56) failed to build because typing checks did not pass.
The reason is unclear, but Fiona figured out that the build failed when adding owid-catalog as a requirement (and hence upgrading pandas above version 1.3.2). For the time being, we decided to ignore type checks on all files that triggered the build error.

**Comment by pabloarosado** [comment]
This PR was created because [this other PR](https://github.com/owid/importers/pull/56) failed to build because typing checks did not pass.
The reason is unclear, but Fiona figured out that the build failed when adding owid-catalog as a requirement (and hence upgrading pandas above version 1.3.2). For the time being, we decided to ignore type checks on all files that triggered the build error.

**Review by pabloarosado — APPROVED** [review]

**Review by larsyencken — APPROVED** [review]
It looks fine, though I can't see any reason why not to use a much newer pandas still.

On skipping type checks, it looks like the chat revision selector and the utils modules might still benefit from having them enabled. But the data team can choose the workflow here.

As mentioned, my hope is we can migrate entirely off this repo and completely deprecate it in the coming two months.

**Comment by pabloarosado** [comment]
> It looks fine, though I can't see any reason why not to use a much newer pandas still.
> 
> On skipping type checks, it looks like the chat revision selector and the utils modules might still benefit from having them enabled. But the data team can choose the workflow here.
> 
> As mentioned, my hope is we can migrate entirely off this repo and completely deprecate it in the coming two months, basically by building nearly everything new as ETL steps.

Thanks @larsyencken. I can actually update Pandas to the latest version in a different PR. I think the main issue was adding owid-catalog, as @spoonerf pointed out.
If anyone wants to bring those checks, they can remove the `# type: ignore` of a specific module and make the appropriate changes to pass the checks. It may be easier to do that one by one than solving all typing issues in all modules at once.

**Pull request merged**
